"""rename address

Revision ID: 025ef5975663
Revises: bb248c5f4e7d
Create Date: 2024-02-21 21:59:43.964468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '025ef5975663'
down_revision = 'bb248c5f4e7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('departments', sa.Column('location', sa.String(), nullable=True))
    #op.drop_column('departments', 'address')
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('departments', sa.Column('address', sa.VARCHAR(), nullable=True))
    #op.drop_column('departments', 'location')
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
