"""rename department

Revision ID: bb248c5f4e7d
Revises: aa241409305b
Create Date: 2024-02-21 21:54:43.146316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb248c5f4e7d'
down_revision = 'aa241409305b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_table('departments',
    #sa.Column('id', sa.Integer(), nullable=False),
    #sa.Column('name', sa.String(), nullable=False),
    #sa.Column('address', sa.String(), nullable=True),
    #sa.PrimaryKeyConstraint('id')
    #)
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_table('department',
    #sa.Column('id', sa.INTEGER(), nullable=False),
    #sa.Column('name', sa.VARCHAR(), nullable=False),
    #sa.Column('address', sa.VARCHAR(), nullable=True),
    #sa.PrimaryKeyConstraint('id')
    #S)
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
